// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicApi.Data;

#nullable disable

namespace MusicApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MusicApi.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = "2:12",
                            Genre = "Punk",
                            Title = "May 16th"
                        },
                        new
                        {
                            Id = 2,
                            Duration = "3:12",
                            Genre = "Punk",
                            Title = "Fall Back Down"
                        },
                        new
                        {
                            Id = 3,
                            Duration = "3:15",
                            Genre = "Punk",
                            Title = "Sophomore Slump or Comeback of the Year"
                        },
                        new
                        {
                            Id = 4,
                            Duration = "1:56",
                            Genre = "Punk",
                            Title = "Red Hot Moon"
                        },
                        new
                        {
                            Id = 5,
                            Duration = "2:17",
                            Genre = "Metal",
                            Title = "Sabbath Bloody Sabbath"
                        },
                        new
                        {
                            Id = 6,
                            Duration = "2:46",
                            Genre = "Blues",
                            Title = "Alabama Bound"
                        },
                        new
                        {
                            Id = 7,
                            Duration = "4:10",
                            Genre = "Rocksteady",
                            Title = "Ain't No Joke Bein' Broke"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
